modLoader="kotlinforforge"
loaderVersion="[1.10,)" # Require at least 1.9.x
license='LGPL'

[[mods]]
    modId="create_jetpack"
    version="${file.jarVersion}"
    displayName="Create Jetpack"
    authors="possible_triangle"
    description='''Jetpacks for the create mod'''

[[dependencies.create_jetpack]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.create_jetpack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.create_jetpack]]
    modId="create"
    mandatory=true
    versionRange="[mc1.16.5_v0.3.2,)"
    ordering="AFTER"
    side="BOTH"
